loots:
  -
    category: fish
    item: COD
    title: '<color:#2b6eff>Треска</color>'
    cost: 5
  - category: fish
    item: PUFFERFISH
    title: '<color:#2b6eff>Рыба Фуга</color>'
    cost: 5
  - category: fish
    item: SALMON
    title: '<color:#2b6eff>Лосось</color>'
    cost: 5
  - category: fish
    item: TROPICAL_FISH
    title: '<color:#2b6eff>Тропическая рыба</color>'
    cost: 10
lang:
  sold: '<color:#2b6eff>Ты продал рыбу на сумму %amount%</color>'